### ISSUE TITLE
When disabled `infoview` module, throws `:lua` error after attempting to open

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#101]
First noticed this because of the fact that [suggested mappings are set regardless of whether their corresponding modules are `enable = true`'d](https://github.com/Julian/lean.nvim/blob/afdd047db65da46780825e4b303b3dbabbebf6bf/lua/lean/init.lua#L15).

For example, if you set `enable = false` for the `infoview` module, if you then try `<LocalLeader>i` in a Lean file you'll get a `:lua` error.

~~I believe we should fix this on a fundamental level by disabling calls to the public functions of a module if it has been disabled - using metatables, I think this should be doable without having to change the functions themselves.~~
EDIT: see discussion below

**Comment by Julian** [comment]
Not sure what I think about the general case, but that sounds more like an infoview bug to me, I'd expect the keybind in that case to simply open / enable the infoview.

(This is part of why I didn't really want to distinguish between autoopen and enabled infoviews)

**Comment by rish987** [comment]
In that case what do you think about having the infoview enabled by default? And removing the `enable` option altogether? Personally I can't think of a way that setting `enable = false` could be useful.

**Comment by Julian** [comment]
I think I am in favor of removing the option altogether, and only having `autoopen` agree.

**Comment by rish987** [comment]
Sounds good, will do. This brings up the question of whether we should do the same for the `lsp.lua` module. IMO we shouldn't because I see an actual use case there of wanting to disable LSP to make things faster in general. And because at the moment there isn't anything in there that can be called which can cause error messages (but this does mean we need to be careful about not introducing anything like this in the future). Let me know whether you agree.

**Comment by Julian** [comment]
Yep +1 from me!
