### ISSUE TITLE
Infoview treesitter

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#121]
Especially in light of #118 and #113, it would be incredibly useful to give nvim some awareness of how infoview messages are fundamentally structured. This could also address some of the concerns raised at #114 about how to make things more vim-like so we can use general APIs. Treesitter is new to me but I'd be happy to do some more research into it!

**Comment by Julian** [comment]
It'd be pretty easy to write a tree-sitter parser for the infoview (I had it in mind awhile back before @gebner swooped in with a great simple vimscript one :P).

The thing is the interop is better I think if everything is tree-sittered (you're going to need to parse lean terms don't forget). But it's not a strict requirement. 

Yeah feel free to investigate (or I can possibly give some tips obviously if you need em).

**Comment by rish987** [comment]
Yep I'll definitely be working on this soon. The main point of this is to be able to map from a cursor position in the infoview to our corresponding Lua object, which could enable a lot of cool features related to #118.

It would be very interesting to investigate whether we can make a general treesitter-based TUI for vim buffers that simulates the context-awareness of HTML using some kind of hidden text wrappers. AFAIK this doesn't exist yet? So initially we'll probably have to do this by hard-coding our infoview-related symbols into the treesitter config.

**Comment by rish987** [comment]
Or, to start, we can get this HTML-like functionality just with simple position math (no treesitter needed), and evolve into treesitter over time.
