### ISSUE TITLE
[Bug] `Error executing vim.schedule lua callback` [...] `lean: Executable not found`

### ISSUE THREAD

**Issue by luiz00martins** [Julian/lean.nvim#132]
I installed `lean.nvim` using the following steps:
 1. Running `sudo npm install -g lean-language-server` to install the language server
 2. Adding the plugin to Packer with `use{'Julian/lean.nvim', requires = {'neovim/nvim-lspconfig', 'nvim-lua/plenary.nvim'}}`
 3. Running `:PackerSync`

However, upon attempting to open a `.lean` file, I received the following error:
```
Error executing vim.schedule lua callback: .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:105: lean: Executable not found
stack traceback:
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:105: in function 'new'
        ...nvim/site/pack/packer/start/lean.nvim/lua/lean/_util.lua:36: in function 'subprocess_check_output'
        ...nvim/site/pack/packer/start/lean.nvim/lua/lean/lean3.lua:43: in function '__detect_elan'
        ...re/nvim/site/pack/packer/start/lean.nvim/lua/lean/ft.lua:5: in function 'cb'
        vim.lua:277: in function <vim.lua:277>
```

So I copied the setup in the [Configuration and Usage section of the README](https://github.com/Julian/lean.nvim#configuration--usage), but to no avail. Interestingly, after that, running `:source $MYVIMRC` also yields this error:
```
E5108: Error executing lua vim/shared.lua:225: after the second argument: expected table, got nil
stack traceback:
        vim/shared.lua:225: in function 'tbl_extend'
        ...m/site/pack/packer/start/lean.nvim/lua/lean/infoview.lua:433: in function 'enable'
        .../nvim/site/pack/packer/start/lean.nvim/lua/lean/init.lua:40: in function 'setup'
        /home/luiz00martins/.config/nvim/plugins.lua:592: in main chunk
        [C]: in function 'require'
        [string ":lua"]:10: in main chunk
```

Line `592` is where I call `require('lean').setup{`, so it seems the setup call is failing.

---

After some pruning, I have reduced my `plugins.lua` to this configuration:
```lua
require('packer').startup(function(use)
  use{"wbthomason/packer.nvim"}
  use{'Julian/lean.nvim', requires = {'neovim/nvim-lspconfig', 'nvim-lua/plenary.nvim'}}
end)

-- If you don't already have a preferred neovim LSP setup, you may want
-- to reference the nvim-lspconfig documentation, which can be found at:
-- https://github.com/neovim/nvim-lspconfig#keybindings-and-completion
-- For completeness (of showing this plugin's settings), we show
-- a barebones LSP attach handler (which will give you Lean LSP
-- functionality in attached buffers) here:
local function on_attach(client, bufnr)
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', {noremap = true})
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', {noremap = true})
    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
end

require('lean').setup{
  -- Enable the Lean language server(s)?
  --
  -- false to disable, otherwise should be a table of options to pass to
  --  `leanls` and/or `lean3ls`.
  --
  -- See https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#leanls for details.

  -- Lean 4
  lsp = { on_attach = on_attach },

  -- Lean 3
  lsp3 = { on_attach = on_attach },

  -- Abbreviation support
  abbreviations = {
    -- Set one of the following to true to enable abbreviations
    builtin = false, -- built-in expander
    compe = false, -- nvim-compe source
    snippets = false, -- snippets.nvim source
    -- additional abbreviations:
    extra = {
      -- Add a \wknight abbreviation to insert ♘
      --
      -- Note that the backslash is implied, and that you of
      -- course may also use a snippet engine directly to do
      -- this if so desired.
      wknight = '♘',
    },
    -- Change if you don't like the backslash
    -- (comma is a popular choice on French keyboards)
    leader = '\\',
  },

  -- Enable suggested mappings?
  --
  -- false by default, true to enable
  mappings = false,

  -- Infoview support
  infoview = {
    -- Automatically open an infoview on entering a Lean buffer?
    autoopen = true,
    -- Set the infoview windows' widths
    width = 50,
  },

  -- Progress bar support
  progress_bars = {
    -- Enable the progress bars?
    enable = true,
    -- Use a different priority for the signs
			priority = 10,
  },
}
```

Both errors still appear, so I assume it's not because of conflicts with other plugins.

---

Even with this very minimal `plugins.lua` setup, the first error still persists:
```lua
require('packer').startup(function(use)
  use{"wbthomason/packer.nvim"}
  use{'Julian/lean.nvim', requires = {'neovim/nvim-lspconfig', 'nvim-lua/plenary.nvim'}}
end)
```

---

System details:
 - Pop_OS 21.04
 - NVIM v0.6.0-dev+155-g15b736d6e
 - npm 7.5.2

**Comment by rish987** [comment]
By chance do you not have `elan` installed according to [the instructions at `nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#lean3ls)? (It seems like we don't even mention this in the README at the moment, which we definitely should)

**Comment by luiz00martins** [comment]
Indeed, this solved the problem! I come from Isabelle, where the `isabelle` binary *is* the language server, so I didn't know that in lean the kernel and LS were separate entities. It would definitely help having that noted it the README.

I can now open a `.lean` file and have the infoview running and working. Thanks!

---

However, the other error still persists, specifically in the line where I call `require('lean').setup{`. After running `:source $MYVIMRC`, this pops up:

```
E5108: Error executing lua vim/shared.lua:225: after the second argument: expected table, got nil
stack traceback:
        vim/shared.lua:225: in function 'tbl_extend'
        ...m/site/pack/packer/start/lean.nvim/lua/lean/infoview.lua:433: in function 'enable'
        .../nvim/site/pack/packer/start/lean.nvim/lua/lean/init.lua:40: in function 'setup'
        /home/luiz00martins/.config/nvim/plugins.lua:592: in main chunk
        [C]: in function 'require'
        [string ":lua"]:10: in main chunk
```

It's worth noting that this error does not happen when starting up neovim, nor when I open a `.lean` file. Those work fine. It only happens when I re-source manually with `:source` (which is a bit puzzling).

**Comment by Julian** [comment]
Making running `setup{}` idempotent might take a bit more work, but probably isn't prohibitively hard.

For the minute you can ensure it only runs once by doing it in e.g. `~/.config/nvim/plugin/lean.lua` rather than in your `init.{vim,lua}` and then not re-sourcing that, if that helps.

I can add a note ensuring we mention you need to install Lean 3 as well to the README in a second -- for Lean4 things work the way you mentioned (in Isabelle).

Also thanks for the feedback! Share any more you've got.

**Comment by Julian** [comment]
@luiz00martins I've added a quick note to the README to note that Lean 3 is a separate install.

I'll track a separate (new) ticket for allowing re-running `require'lean'.setup{}` multiple times, but I can't say when someone'll get around to it (patches certainly welcome). Otherwise hopefully stuff here is worked out, but let us know if you have more feedback, hopefully things are going well!
