### ISSUE TITLE
Replace any compe support with nvim-cmp

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#140]
[nvim-compe was deprecated a bit back](https://github.com/hrsh7th/nvim-compe#warning) and replaced by [nvim-cmp](https://github.com/hrsh7th/nvim-cmp).

(There's also tabnine support for cmp [here](https://github.com/tzachar/cmp-tabnine) which may be worth trying given some success in vscode-land for Lean)

**Comment by Karthik-Dulam** [comment]
Currently the readme.md file conflicts in the recommended plugin to use.
Under "Installation"
`Plug 'hrsh7th/nvim-cmp'        " For LSP completion`
And under "Features" and in the "Recommended configuration"
> Abbreviation (unicode character) insertion, can also provide a [nvim-compe](https://github.com/hrsh7th/nvim-compe) source.
```  -- Abbreviation support
  abbreviations = {
    -- Set one of the following to true to enable abbreviations
    builtin = false, -- built-in expander
    compe = false, -- nvim-compe source```

At the moment what is the recommended plugin to use of the two?

**Comment by gebner** [comment]
I'd use `builtin = true`, I wonder if we should make that the default.
