### ISSUE TITLE
Moving the cursor over regions can garble the infoview with concatenated goal state

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#142]
See this recording:

https://user-images.githubusercontent.com/329822/135878886-ab4ee5ca-18c7-4770-ad7b-c95c0f59d6e8.mov

where somehow holding down `l` (or `h`) and moving over the intermediate regions leaves the infoview with somehow multiple copies of the state once the cursor lands.

Moving the cursor again "fixes" / re-renders correctly.

**Comment by gebner** [comment]
I believe that's a side effect of #141 and what the lock was supposed to prevent.  I think it should be enough to insert `if not tick:check() then return end` at the relevant places and before writing the text to the window.

**Comment by rish987** [comment]
Just left some comments on #141 that hopefully clear up why there was that error. I think 2589253 should be reverted, and we can make the `buf_request`s have a timeout (upon which it error-prints) so hanging is impossible.

**Comment by rish987** [comment]
In addition, we can replace some direct calls with `pcall`s in key places so we can "catch" a runtime error and release the lock if there is one.

**Comment by gebner** [comment]
I tried adding pcalls first, but that didn't catch the rpc error. :-(

**Comment by rish987** [comment]
The RPC error originates from my change at 27977d1 where I forgot to make `value` the _third_ parameter after calling the event with `render_fn` (so `render_fn` is what it tried to serialize).
