### ISSUE TITLE
Make calling require'lean'.setup{} idempotent

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#145]
Users occasionally will put this in a file they reload or re-source, so it'd be nice if it were able to be run multiple times.

Right now most of the state issues are simply with initializing global configuration, so this may not be too difficult to do.

(See #132 for some context.)

Relates to #39.

**Comment by 4e554c4c** [comment]
the solution in my config
```lua
local success, err = pcall(function ()
  require('lean').setup{}
end)
if not success then
  print(err)
end
```
