### ISSUE TITLE
Positioning of widget popup is off with line wrapping

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#147]
When a line is wrapped, then popups on the second line overlap the line itself.  If you click here:

![before_click](https://user-images.githubusercontent.com/313929/135988311-9dcbe384-f253-41e6-9281-61fa48ec54a8.png)

Then the popup opens right over the cursor:

![after_click](https://user-images.githubusercontent.com/313929/135988440-05fabeaf-0311-4fed-b65e-fbf9dd45e1cd.png)

**Comment by gebner** [comment]
It gets worse when you open a nested tooltip, the nested tooltip then appears on the other side of the editor at the top-left corner.

**Comment by rish987** [comment]
> the nested tooltip then appears on the other side of the editor at the top-left corner.

Are you using a neovim version with neovim/neovim#14770?

**Comment by gebner** [comment]
Ah, so that's why I couldn't reproduce the error after upgrading to 0.5.1 today!  The positioning on wrapped lines also works now!

**Comment by Julian** [comment]
@gebner are you ok with us supporting 2 versions at a time? (i.e. tactically dropping 0.5 from CI now that 0.5.1 is there?) This is essentially the upstream supported versions, they support latest + latest release.

**Comment by gebner** [comment]
For now it doesn't cost us much to keep supporting 0.5.0.  0.5.1 only got released last week, and 0.5.0 is still the latest version in a lot of distributions: https://repology.org/project/neovim/versions

So my preferred approach is to keep supporting 0.5.0, 0.5.1, ..., master as long as possible.  We should only drop 0.5.0 support once 0.5.1 has been out for a couple months, and we really need features from 0.5.1.

**Comment by Julian** [comment]
Fine :)
