### ISSUE TITLE
Infoview does not update while processing

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#162]
When a file is still processing, the infoview only shows the unhelpful "Processing file..." message.  It should show the available diagnostics and tactic state for already-processed regions.

**Comment by rish987** [comment]
From #165:
> AFAICT it's an upstream Lean 4 server issue. It seems to not be responding to our Lean.Widget.getInteractiveDiagnostics RPC calls until the file is fully processed, so many of our async calls are left hanging indefinitely.

One workaround we could use is to put a timer on `util.a_request` after which it calls the handler with error, and let it fall back to the plain diagnostics. But a server fix, at least to respond error rather than not respond at all, is certainly needed.

**Comment by gebner** [comment]
Thanks for debugging that!  Would it be enough if the getInteractiveDiagnostics command would return once Lean is done with the corresponding line (but not necessarily the whole file)?  Or would the infoview still get stuck?

**Comment by rish987** [comment]
We don't send the request at all if we detect the line is processing. So as long as it's responsive after `fileProgress` indicates that line is done processing, that will work. Though ideally it seems it should always be responsive regardless.
