### ISSUE TITLE
nvim-cmp inserting control-f character

### ISSUE THREAD

**Issue by ram02z** [Julian/lean.nvim#168]
Hey, I understand that nvim-cmp is not supported as of now, but this bug is a rather peculiar one. I have just started using lean and whenever I write a begin end block, the end always gets a Control-f character appended to it. I disabled nvim-cmp entirely and I cannot reproduce this issue. I use manual completion and this occurs without having to even invoke the menu. This occurs on `.lean3` files, I haven't been able to figure how to specify that `.lean` files are lean3 automatically.

Example file: (you could remove the end and try it yourself)
```lean
variables P Q R : Prop

example : (P → (Q → (P ∧ Q))) :=
begin
  assume p q,
  constructor,
  exact p,
  exact q,
end
```

My cmp setup: https://gist.github.com/ram02z/3a5b8f26dec39d46345b22c7445cd386

My lean.nvim setup: 
```lua
require("lean").setup{
  lsp3 = { on_attach = on_attach },
  lsp = { enable = false },
  mappings = true,
}
```

Neovim version: 
`NVIM v0.6.0-dev-gb3e0d6708`

**Comment by Julian** [comment]
OK, the second fix seems to work here -- does it for you as well?

**Comment by ram02z** [comment]
> OK, the second fix seems to work here -- does it for you as well?

Yeah the fix works now, thanks!

**Comment by ram02z** [comment]
After https://github.com/hrsh7th/nvim-cmp/issues/443, the same issue is back. 

Why do we append `indentkeys` instead explicitly setting it? (I am asking because I don't understand the default indentkeys)

https://github.com/Julian/lean.nvim/blob/main/indent/lean3.vim#L6

**Comment by Julian** [comment]
Thanks
