### ISSUE TITLE
[Bug] LSP not returning anything, despite it being properly loaded and running.

### ISSUE THREAD

**Issue by luiz00martins** [Julian/lean.nvim#170]
I have Lean 3 (version 3.33.0) and the `lean-language-server` (version 3.1.1) installed. Also, I have `lsp-config` and `lean.nvim` installed. For some context, I was using `lean.nvim` just fine 2-4 weeks ago. After some time not writing any Lean, I opened it and found it was not functioning.

Basically, the server is not returning any feedback, as in this example:

*My cursor is at a line where the theorem should be shown in the infoview, but it is empty. 2 lines down from the cursor there's a line with some random text, but I get no complaint from the LSP*
![Screenshot from 2021-10-12 07-20-20](https://user-images.githubusercontent.com/43142209/136941185-b45f1665-3332-4c17-aad7-e167edb52cf6.png)

However the LSP seems to be running fine. Executing `:checkhealth lean` returns no error:
```
health#lean#check
========================================================================
## lean.nvim
  - OK: `lean --version`
  - INFO: Lean (version 3.33.0, commit a0fb1e8c7ac8, Release)
  - OK: `lean-language-server`
```

Furthermore, running `:LspInfo` shows that the server is running fine:
![Screenshot from 2021-10-12 07-45-02](https://user-images.githubusercontent.com/43142209/136941690-3f628c26-e527-4f27-9404-0a8fa956b43e.png)

Since everything is apparently installed and running, with no errors or warnings, I'm lost as to why the server is not returning any result.

**Comment by Julian** [comment]
To add to @gebner's list of possible solutions without introducing poor UX, I think a third reasonable option is simply to add a "default filetype" configuration option, and use that for standalone files with no `leanpkg.toml`. Still default to `lean` for forward compatibility, but allow users to pick `lean3`.

**Comment by ram02z** [comment]
I am also experiencing a similar issue. When I open a `.lean` file, standalone or not, the filetype doesn't change to `lean3` so  `lean3ls` doesn't get attached to the buffer. One way I can remedy this, without having to set the filetype to lean3 everytime I open a lean file, is to change the file extension to `lean3`, but that seems to break abbreviations. Additionally, the README states `<LocalLeader>3` forces the buffer into Lean 3 mode, but the mapping doesn't work for me (I have `mappings = true` in my config and other mappings work fine)

**Comment by ram02z** [comment]
> We'll fix this bug with standalone file detection which should make you not need to do this again, but in the interim you can of course yourself do `nnoremap <LocalLeader>3 :set ft=lean3<CR>`.

Ah, I am using an autocommand to default to lean3 for the meantime since I don't think I will be using lean 4 anytime soon anyway. Looking forward to the fix!

**Comment by Julian** [comment]
We've just merged the above PR, so you can now set `ft = {default = "lean3" }` if you want standalone files to be Lean 3.

Let us know if that helps!
