### ISSUE TITLE
Infoview cannot be reopened

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#173]
I can reproduce this with both `se hid` and `se nohid`:

 - `:e some_file.lean`
 - `:q`
 - (Now you're in the infoview.)
 - `:e another_file.lean`
 - `:LeanInfoviewToggle`

Then I get the error `infoview.lua:150: Vim:E444: Cannot close last window`.  Apparently the infoview believes it is still open.

**Comment by Julian** [comment]
I don't think this is actually fixed, I still see the same behavior (and the pending test I just tried to re-enable still fails). @gebner lemme know if I'm missing something.

**Comment by gebner** [comment]
Indeed, the bug still seems to be there.  I though I'd fixed it by checking `vim.api.nvim_win_is_valid` first, but that clearly wasn't the issue.

**Comment by Julian** [comment]
(OK, now it's fixed, with a one word change.)
