### ISSUE TITLE
Infoview sometimes hangs

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#176]
Unfortunately, I don't have a good repro.  Sometimes after working on a Lean 4 file for a long time, the infoview just stops updating.  Is there anything I can run to diagnose this?

**Comment by gebner** [comment]
> Also try printing before and after the calls that directly or indirectly invoke vim.lsp.buf_request or similar to see if one of them is getting stuck...

Wait, if one these calls doesn't return the infoview gets stuck?

**Comment by rish987** [comment]
> Ok, it got stuck again with 'Processing file...'

[We abort the update if we detect the line is still processing](https://github.com/Julian/lean.nvim/blob/1c26540be3159cf474499fe46a43afa616689210/lua/lean/infoview.lua#L650) -- perhaps the server neglected to update us on the progress for some reason?

**Comment by rish987** [comment]
@Julian Also Lean 4? I've been investigating Lean 3 stdlib metaprogramming for a few days now and haven't had a hang yet, but I think I _might_ have seen it hang while testing in Lean 4.

**Comment by Julian** [comment]
Lean 4 yep

**Comment by Julian** [comment]
@gebner do you still see this?

**Comment by gebner** [comment]
I haven't seen this for some time now.
