### ISSUE TITLE
Weird Error message when closing a lean file occasionally.

### ISSUE THREAD

**Issue by zoomiti** [Julian/lean.nvim#188]
It seems to not happen to every file but closing a lean file always gives me this error message:

```console
Error detected while processing WinEnter Autocommands for "<buffer=2>":
E5108: Error executing lua ...iti/.config/nvim/plugged/lean.nvim/lua/lean/infoview.lua:503: line value outside range
```

I am using the vanilla suggested LSP settings from the README

**Comment by rish987** [comment]
What do you mean by closing the file? Are you deleting the buffer?

**Comment by zoomiti** [comment]
If by deleting the buffer you mean ```:wq``` or ```:x``` then yes.

**Comment by rish987** [comment]
Hmm I'd need more details to reproduce, what file is it and is the infoview open when you close it? Do you enter the infoview immediately after closing the file?

**Comment by zoomiti** [comment]
I can send you the file in a gist or here if you prefer. And the infoview is open when I delete the buffer but the error interrupts the process of deleting the buffer so both are technically still open. Once I press enter though the buffer finishes closing and I am left with just the infoview. I can also record this if you want to see it, in case you can't reproduce it.

**Comment by Julian** [comment]
Let's close now that 0.6 is out officially, but we can reopen either way if there's a way to reproduce this.
