### ISSUE TITLE
Nix buildVimPlugin compatibility & support

### ISSUE THREAD

**Issue by Anderssorby** [Julian/lean.nvim#192]
I've tried a simple nix flake setup for this plugin, but I guess I'm missing some dependencies:
In https://github.com/Anderssorby/lean.nvim/tree/acs/add-nix-flake running `nix build`
```
vimplugin-lean.nvim> unpacking sources
vimplugin-lean.nvim> unpacking source archive /nix/store/lvrmjq6x8hxq07v5gn4wbyi9dwfsr4ap-fzjpvalizgp1l9w71ij4ni3nd026c0ln-source
vimplugin-lean.nvim> source root is fzjpvalizgp1l9w71ij4ni3nd026c0ln-source
vimplugin-lean.nvim> patching sources
vimplugin-lean.nvim> configuring
vimplugin-lean.nvim> no configure script, doing nothing
vimplugin-lean.nvim> building
vimplugin-lean.nvim> build flags: SHELL=/nix/store/wv35g5lff84rray15zlzarcqi9fxzz84-bash-4.4-p23/bin/bash
vimplugin-lean.nvim> nvim --noplugin -u scripts/minimal_init.lua -c "lua require'lean'.setup"{}""
vimplugin-lean.nvim> =11;?(BError detected while processing /build/fzjpvalizgp1l9w71ij4ni3nd026c0ln-source/
vimplugin-lean.nvim> scripts/minimal_init.lua:
vimplugin-lean.nvim> line    1:
vimplugin-lean.nvim> E194: No alternate file name to substitute for '#': vim.opt.display = 'lastline'
vimplugin-lean.nvim> line    2:E303: Unable to create directory "/homeless-shelter" for swap file, recovery imp
vimplugin-lean.nvim> ossible: permission denied
vimplugin-lean.nvim> "directory" [New File]Cannot open file "directory"
vimplugin-lean.nvim> E303: Unable to create directory "/homeless-shelter" for swap file, recovery impossible: permission denied
vimplugin-lean.nvim> "=" [New File]Cannot open file "="
vimplugin-lean.nvim> E303: Unable to create directory "/homeless-shelter" for swap file, recovery impossible: permission denied
vimplugin-lean.nvim> "''" [New FileCannot open file "''"
vimplugin-lean.nvim> E480: No match: opt
vimplugin-lean.nvim> line    4:
vimplugin-lean.nvim> E492: Not an editor command: local __file__ = debug.getinfo(1).source:match("@(.
vimplugin-lean.nvim> *)$")
vimplugin-lean.nvim> line    5:
```

**Comment by RaitoBezarius** [comment]
see https://github.com/NixOS/nixpkgs/pull/144282

**Comment by Julian** [comment]
Is there what more to do in this repo after that PR in the nixpkgs repo? Or given that it's now merged are you saying we should close this ticket?

**Comment by Julian** [comment]
Going to close since I assume that was the implication above but if that's not the case and there's something left to be done let me know!

**Comment by Anderssorby** [comment]
@Julian There is more to be done since that PR didn't solve the problem right away. I'm also using a different function to build the vim plugin which doesn't read the `dependencies` attribute apparently. I've not looked at this too much yet.

**Comment by Julian** [comment]
Got it. OK, and the request here is basically to add a nix flake to the repo?

**Comment by Anderssorby** [comment]
Yes, so I can load it into my env without having to wait for nixpkgs.

**Comment by Julian** [comment]
Assuming this is even still relevant (given it seems nixpkgs stays relatively up to date with the repo here from what I can tell), and given I don't personally know how to do this or have access to a nixOS machine anymore, going to close this, but if you or anyone is still interested a PR to do whatever is needed is definitely fine with me.
