### ISSUE TITLE
Inserting a space before ⟨ crashes the server

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#217]
I'm not sure if this is a bug in the lean 4 server or in nvim 0.6.

To reproduce, create a file with the single character `⟨`.  Then insert a space before.  You should see this error:
```
Watchdog error: Cannot read LSP message: offset 119: unexpected character in object
```

The lean 3 server seems to be fine.  Do you see the same error?

**Comment by Julian** [comment]
Yes I see that crash too.

**Comment by Julian** [comment]
Apparently I am even failing at understanding how to patch out the lean4 stdlib. I changed `src/Lean/Data/Json/Parser.lean`'s implementation of `parse` to be able to see what the supposed invalid JSON looks like in the error message, ran `lean -o` to recreate an olean, and doing so appears to not have changed the error message. Surely I'm doing something wrong, I can see my new olean is being used (if say I create a new declaration I see it at runtime) but I must be modifying the wrong function somehow...

**Comment by gebner** [comment]
> Apparently I am even failing at understanding how to patch out the lean4 stdlib.

The json parser is compiled into the lean binary (actually into `libleanshared.so`), so you'll need to compile everything.

**Comment by Julian** [comment]
Aha. Thanks for explaining!

**Comment by mjlbach** [comment]
This should hopefully be fixed now.

**Comment by Julian** [comment]
Thanks! Indeed seems like it.
