### ISSUE TITLE
Annoying 32801 error in :messages

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#225]
I often get the following error in `:messages` (at least I think that's what it is, it's red and interrupts typing):
```
leanls: -32801: The file worker has been terminated. Either the header has changed, or the file was closed, or the server is shutting down.
```

I'm not sure what triggers this, but it would be great to suppress these errors.

**Comment by gebner** [comment]
Apparently this is already fixed upstream, maybe I should switch to neovim master at some point (currently on 0.6.0 + 5 backported PRs).

https://github.com/neovim/neovim/pull/16904

**Comment by Julian** [comment]
Yes, I noticed these (and then updated and they went away). You probably should switch though honestly, things are still moving fast enough that being on 0.6.0 I think is just a worse experience.
