### ISSUE TITLE
Start Lean 4 server using `lake serve`

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#229]
See also https://github.com/leanprover/vscode-lean4/pull/97

Slight complication is that we should only start `lake serve` if `lake --version` is at least 3.0.0.  (Older versions don't have a working `lake serve` command and it's hard to tell if it failed because of the lake version or something else.)  An additional issue is that we need to work for elan to download the lean version to execute `lake --version`.  I hope we can make it so that this doesn't block neovim (like the filetype detection did).

This is necessary to make the workspace symbol search work in mathlib4. https://github.com/leanprover/lake/pull/46#issuecomment-1028985404

**Comment by Julian** [comment]
> Slight complication is that we should only start lake serve if lake --version is at least 3.0.0.

Can we decide by matching on the contents of `lean-toolchain`? Or do we really need to run the subprocess?

**Comment by gebner** [comment]
> Can we decide by matching on the contents of lean-toolchain (i.e. from the Lean 4 version)?

In my experience with the current Lean 3 version check, this is pretty flaky if you use `3dev` or something like that as a version.  For `lake serve` it gets even more complicated as you'd need to check that the version is at least `nightly-2022-02-01` or `4.0.0-m3`.  If it is a custom release tag like `gebner/lean4:fancy_proposed_feature` then you're completely out of luck.

> Or do we really need to run the subprocess?

I don't really see a way around it.  I'm not sure why the check was so disruptive for the lean version.  Maybe we should've just used async for that?

> Can you upgrade Lake even though it's vendored on an older Lean 4?

Theoretically it is not impossible.  But it's very much against all recommendations, and weird failures are to be expected if you run a non-matching lake version.

**Comment by Julian** [comment]
> In my experience with the current Lean 3 version check, this is pretty flaky if you use 3dev or something like that as a version.

(I think this should be easy to fix FWIW, the regex is naive but catching something like that should be easy?)

> I don't really see a way around it. I'm not sure why the check was so disruptive for the lean version. Maybe we should've just used async for that?

But fair enough, guess we go back to that (I don't remember if there was a reason we stopped doing it but git will hopefully know).

**Comment by Julian** [comment]
Blehhh this completely breaks single file mode until there's a release with the fallback behavior :/

**Comment by Julian** [comment]
OK, in case anyone else happens to run into ^, so far so good on building `lake` from source (via `lake build` in a clone of `lake`) and just using that for now until the Lean 4 repo updates its embedded lake.

FWIW it seems this isn't unsupported, at least the Lake repo seems to even "recommend" it:

> Note that the Lake included with Lean is not updated as frequently as this repository, so some bleeding edge features may be missing. If you want to build the latest version from the source yourself, check out the build instructions at the bottom of this README.

But my question was probably imprecise, I wasn't asking about specifically upgrading the embedded lake, I just wanted to know if `lean --version` determined `lake --version` in supported configs (and it seems the answer is "no").

**Comment by Julian** [comment]
With `lake` 3.1.0(-pre), it works here, yes:

https://user-images.githubusercontent.com/329822/152988933-d62857d1-2bc2-4dd4-9e6a-f2ee8429af4d.mov

**Comment by gebner** [comment]
I think the server still uses the bundled lake for `lake print-paths`.  You need to `export LAKE=(which lake)` to override it.  I get the following error:
```
▶ 1:1-1:2: error:
`/home/gebner/lake/build/bin/lake print-paths Init` failed:

stderr:
Error parsing './lakefile.lean'.  Please restart the lean server after fixing the Lake configuration file.
```

**Comment by Julian** [comment]
I... see. Weird. Doesn't seem like the fallback is super useful then.

**Comment by gebner** [comment]
> Doesn't seem like the fallback is super useful then.

Yeah, the fallback wasn't designed so that you could unconditionally run `lake serve`.  Backwards compatibility was always a concern, so we had to implement a fallback to `lean --server` anyhow.

What the current fallback behavior allows is starting `lake serve` whenever a `lakefile.lean` exists and the lake version is new enough.  We no longer need to start `lake serve`, close stdin, and parse the error message to figure that out.
