### ISSUE TITLE
Make goto definition and hovering and other LSP commands work in the infoview

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#23]
In the infoview, it'd be nice if `vim.lsp.buf.definition()` (or hovering, etc.) on a term which is defined in the corresponding buffer functioned similarly to doing so in the original buffer -- i.e. jumps to the definition, etc.

Doing this for terms embedded in e.g. `try this:` messages would also be nice albeit require a bit more work.

**Comment by gebner** [comment]
While this would indeed be nice, there is zero server support for this.

In Lean 3, we had widgets.  These are HTML fragments sent from the server (implemented using a wonderful React-like architecture).  The default HTML renderer for goals then included an event listener for clicks.  When clicked a request went back to the widget in the server, and then the widget told the editor to navigate to the location of the definition.  This was only ever implemented in vscode, as it is built on HTML and React.

For Lean 4, Sebastian has suggested (in private communication) to use virtual files for goals (for better portability between editors).  The server would then say for every goal: this is `lean://12345.lean` with file contents `.... ⊢ ...`.  You could then use standard LSP requests on these virtual files (such as hover or go-to-definition).  We would also like to have an LSP request to e.g. show implicit arguments, maybe by rewriting the virtual file, or by creating a new virtual file where the implicit arguments are expanded.

**Comment by Julian** [comment]
Thanks as usual for the context!

In the interim, doesn't cheating work similarly to what it sounds like the server will ultimately do? I.e. on the client side, maintain a hidden buffer where we copy the contents of the original Lean buffer, and then in the infoview buffer is interacted with, delegate to running something on that hidden buffer? The issue would be making it look like LSP commands but even if we just directly mapped `gd` in the infoview that may already help.

**Comment by gebner** [comment]
> doesn't cheating work similarly to what it sounds like the server will ultimately do?

This is harder than it sounds.  If you maintain a hidden buffer with contents of the original lean file, then the server will parse it again (which takes time and cpu).  If the hidden buffer is empty, you need to replicate at least the `import` and `open` statements.  Then there's the question of how to copy the infoview contents to the buffer.  The goal state `... ⊢ ...` won't parse as it is.  It might parse some of the time if you liberally sprinkle `∀` over it, but it's still super flaky.

I think this would be a lot of work for an unsatisfactory implementation, and I definitely wouldn't prioritize it.

> The issue would be making it look like LSP commands but even if we just directly mapped gd in the infoview that may already help.

This is a good question.  I don't think you can use the LSP client without running an external program (although this would be straightforward PR to neovim).  Overriding the `vim.lsp.buf.definition()` function is an option though via monkey-patching.

**Comment by Julian** [comment]
> I think this would be a lot of work for an unsatisfactory implementation, and I definitely wouldn't prioritize it.

Thanks! That's again good to know.

I assume this may mean #10 and some other things I was hoping for (e.g. yanking the output of `extract_goal` to the clipboard without modifying the buffer) may be similarly hard... that's unfortunate but sounds like the situation in Lean4 may get better which is great.

> This is a good question. I don't think you can use the LSP client without running an external program (although this would be straightforward PR to neovim).

Yeah, it's also I think reasonably easy to do the last mile there with [efm-langserver](https://github.com/mattn/efm-langserver) from what I can tell, but if it doesn't work there isn't much point obviously.

**Comment by gebner** [comment]
There's now a "null" language server meant for this usecase: https://github.com/jose-elias-alvarez/null-ls.nvim

**Comment by gebner** [comment]
I believe this is mostly implemented now with #123.
