### ISSUE TITLE
Make it possible to change infoview orientation on resize

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#239]
Someone (e.g. me) may want to change the infoview orientation from vertical to horizontal on VimResized events if the screen dimensions change to something narrow. We should expose some API someone can bind to that autocmd which follows the normal logic when opening one from scratch.

**Comment by gebner** [comment]
Relatedly, it would be good if took the "screen" dimensions to determine the orientation.  Right now, we use the window dimensions which means that a vertical split changes landscape to portrait layout.

**Comment by Julian** [comment]
> Relatedly, it would be good if took the "screen" dimensions to determine the orientation.

Done in the linked commit, have a look.
