### ISSUE TITLE
Set the infoview cursor to the goal when updating

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#240]
Right now if the infoview contents are too long, we show the top lines.

It seems more natural perhaps to show the goal instead, which is almost the bottom modulo us showing diagnostics below the goal state.

Comments welcome if someone prefers the current behavior.

**Comment by gebner** [comment]
I certainly prefer the current behavior.  Scrolling to the bottom of the diagnostics is rarely what I want.

> It seems more natural perhaps to show the goal instead, which is almost the bottom modulo us showing diagnostics below the goal state.

This is a reasonable compromise.  The full goal should still be shown though if it fits on the screen.  (That is, don't show the last line of the goal as the first line in the infoview.)

**Comment by Julian** [comment]
>  Scrolling to the bottom of the diagnostics is rarely what I want.

The goal is what I was really suggesting as in the body yeah. Essentially `vim.fn.search('^⊢ ', 'c'); vim.cmd('normal z-')` -- i.e. "find first goal, then run z-". Do you still prefer the current behavior to that?

**Comment by gebner** [comment]
Oh sorry, that wasn't really clear to me in the first post.  Scrolling to the ⊢ is fine.
