### ISSUE TITLE
Node Segfaults

### ISSUE THREAD

**Issue by zaxioms** [Julian/lean.nvim#246]
I regularly encounter seemingly random segfaults with the error

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "server is not alive".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v17.7.2
```
Has anyone seen this or know how to fix it?

**Comment by rish987** [comment]
Unfortunately this is pretty common, I've been dealing with it for months. You can do `:LspRestart` when it happens, though that command is a bit broken at the moment (see neovim/nvim-lspconfig#1782). I feel like this could be a fairly simple fix at leanprover/lean-client-js, but haven't had time to investigate recently.

**Comment by Julian** [comment]
In Lean 3, there's a small node shim language server which sits on top of the Lean 3 server.

The message there is one that node shim throws, but it's the Lean 3 server that's segfaulted typically (or sigabrted).  So the real error isn't in that message, it'll be a coredump somewhere.

There's some debugging in #203 -- ultimately I don't know yet what the cause of the segfaults are :/ and have only spent a small bit of time trying to dig into it, but I see these as well, as do others unfortunately.

**Comment by Julian** [comment]
(Anecdotally I saw a lot fewer of them in the past few weeks, but then a lot more recently the past few days :(... but it could just be random chance).

**Comment by Julian** [comment]
I generalized the title of #203, let's move this there, share any debugging info you can, and sorry :(
