### ISSUE TITLE
Deal with orphaned Lean 3 processes

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#249]
When working on mathlib in a case where olean compilation is happening in the background (e.g. with no cache, or whilst working on a lower level file), exiting neovim often orphans `lean --server` processes.

This either is neovim clients not notifying the server or lean-language-server not waiting / killing its child processes once it hears the clients are stopping (I think the latter?).

As a secondary ailment, this often means someone has lots of resources being eaten up by backgrounded lean processes (which may or may not even be making progress?), so when restarting the editor, new processes are starved for resources until they're `kill`ed (or complete, which may take ages). It may be useful for this case to have information about resource usage of lean processes or a count of lean processes be renderable from within the infoview (perhaps behind configuration).

**Comment by rish987** [comment]
Wow. Well, this explains why I've often found the need to restart my machine after making the fatal mistake of accidentally modifying a low-level mathlib file 🤣

No idea yet but yeah I'm guessing it's on the server side.

**Comment by Julian** [comment]
> Wow. Well, this explains why I've often found the need to restart my machine after making the fatal mistake of accidentally modifying a low-level mathlib file 🤣

Yeah it's easy to miss :/ -- I've been aware of it for awhile and probably should have put this here earlier to flag it for others.

> No idea yet but yeah I'm guessing it's on the server side.

Same, I started to look into which LSP method is the one that should be killing the subprocess in `lean-language-server` but then had to do other things, but yeah I think it's there.
