### ISSUE TITLE
Specify location of lsp

### ISSUE THREAD

**Issue by DieracDelta** [Julian/lean.nvim#266]
I have `lean-language-server` installed, but it is not on my path because I am running nix. Is there a place analogous to the `cmd` option in `lspconfig` where I can specify the full path to the lsp?

**Comment by Julian** [comment]
The `lsp3` table is basically passed along as is to `lspconfig`, so you can stick it there. There's an example [here in the wiki if that helps](https://github.com/Julian/lean.nvim/wiki/Configuring-&-Extending#passing-arguments-to-the-lean-server-eg-timeout--memory-settings).

**Comment by DieracDelta** [comment]
That worked, thanks for the quick reply!
