### ISSUE TITLE
ftdetect script references rest of plugin

### ISSUE THREAD

**Issue by 4e554c4c** [Julian/lean.nvim#272]
Hi!
I'd like to only load the `lean.nvim` plugin if im editing a lean file. I'm currently using the packer package manager, so I did
```lua
 use { 'Julian/lean.nvim', ft = { 'lean', 'lean3' }}
```

In order to do this, packer installs `lean.nvim`'s ftdetect script _without_ the rest of the plugin, so that `lean.nvim` can do filetype detection in order to determine if the plugin should be loaded. Unfortunately, `lean.nvim`'s [ftdetect script](https://github.com/Julian/lean.nvim/blob/main/ftdetect/lean3.vim) calls into the plugin itself. Because the plugin isn't loaded at the time, this causes filetype detection to crash.

Getting around this isn't too hard, since the fix is to just do
```lua
 use { 'Julian/lean.nvim', ft = { 'lean', 'lean3' }, module = 'lean'}
```
but it still doesn't seem optimal since this is loading the entire lean plugin when it's not necessary to do so.

It seems like it would be pretty easy to solve this by moving [`main/lua/lean/ft.lua`](https://github.com/Julian/lean.nvim/blob/main/lua/lean/ft.lua) to `ftdetect/lean3.lua` instead of using the vimscript shim.

**Comment by Julian** [comment]
This is probably a vestige from versions of neovim that predate supporting ftdetect in lua. Any chance you're interested in a PR?

**Comment by 4e554c4c** [comment]
yep, I'll send one :smile:  just try to check beforehand that it's desired
