### ISSUE TITLE
Cursor jumps around when infoview is open

### ISSUE THREAD

**Issue by Mateiadrielrafael** [Julian/lean.nvim#286]
I've just created a new lake project. I've opened one of the files, and it seems like whenever the infoview is open, my cursor jumps to the start of the current/an adjacent line as soon as I move it on the right hand side of a definition.

**Comment by Julian** [comment]
Hi, I can't reproduce this, so will need a bit more info on what you're running (versions of the plugin and Lean, and/or the output from `:checkhealth lean`).

**Comment by Mateiadrielrafael** [comment]
My config for the plugin is also pretty basic:
```lua
  require('lean').setup {
    abbreviations = { builtin = true, cmp = true },
    lsp = { on_attach = lspconfig.on_attach, capabilities = lspconfig.capabilities },
    lsp3 = false,
    mappings = true
  }
```

**Comment by Mateiadrielrafael** [comment]
It seems like the jumping actually happens whenever some text appears inside the infoview

**Comment by Mateiadrielrafael** [comment]
Looking at the lsp log, does this mean anything?
```
[WARN][2022-12-01 17:11:36] ...lsp/handlers.lua:112	"The language server leanls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by Julian** [comment]
I don't think that line should mean anything, it possibly has to do with whatever you're setting in `capabilities` in your sample config but I'd have to check.

But yeah the plugin works fine here, can you perhaps include a full config which reproduces this for you that I can try?

**Comment by Julian** [comment]
Let me know if this is still happening.
