### ISSUE TITLE
Distinguish \perp and \bot

### ISSUE THREAD

**Issue by MithicSpirit** [Julian/lean.nvim#296]
The vscode extension distinguishes between them, with one being `⟂` and the other being `⊥` (I'm not sure which is which; I think that the former is \perp but that should be manually confirmed). This nvim extension should probably reflect that in order to improve compatibility.

**Comment by Julian** [comment]
Thanks! Missed this change upstream a few months ago but now should be automatically kept in sync.

Fixed in e80616c64506a339500bf7480801fa50b3f1b450
