### ISSUE TITLE
"Try this" replaces incorrect segment

### ISSUE THREAD

**Issue by grhkm21** [Julian/lean.nvim#313]
Hi. Here's code:

```lean
import Mathlib.Tactic.Basic

open Lean Elab.Tactic Std.Tactic.TryThis

syntax (name := change') "change'" (ppSpace colGt term)? : tactic

elab_rules : tactic
| `(tactic|change'%$tk $[$sop:term]?) => withMainContext do
  let dstx ← delabToRefinableSyntax (← getMainTarget)
  addSuggestion tk (← `(tactic| change $dstx)) (origSpan? := ← getRef)

def f := fun x ↦ x + 1
def g := fun x ↦ x + 1
example : f 3 = 4 := by
  change' a b c d e f g
```
With this code, it is supposed to change the entire line, as specified by `origSpan?`. Apparently it does on VSCode c.f. [Mario](https://leanprover.zulipchat.com/#narrow/stream/239415-metaprogramming-.2F-tactics). However, the plugin doesn't - it replaces it with `f 3 = 4 a b c d e f g`.
![Screenshot 2023-10-19 at 21 20 20](https://github.com/Julian/lean.nvim/assets/83517584/66ca400e-4036-48cc-806a-f23c991bc2a8)
![Screenshot 2023-10-19 at 21 20 25](https://github.com/Julian/lean.nvim/assets/83517584/49c08d13-f4a2-4238-a476-5d8cc06325a8)

**Comment by Julian** [comment]
This seems to work correctly here (now?). I'm on Lean 4.3.0rc1. Can you confirm whether it does or doesn't for you?

**Comment by grhkm21** [comment]
Hi, sorry for the late reply. No, it doesn't work for me. I'm on NVIM v0.9.4, Lean v4.3.0-rc1, Mathlib b6ec7450650a5945bf4244751be4a5cf1fee962f. It's very interesting that it works for you, my understanding is it shouldn't...

Also, I think I have a fix idea, but I haven't gotten to implement it yet. Essentially, we should implement the `.getWidgets` RPC (found [here](https://leanprover-community.github.io/mathlib4_docs/Lean/Widget/UserWidget.html#Lean.Widget.getWidgets)) and use those directly to get the replacement range (and the js widget source code, which we ignore for now).

**Comment by Julian** [comment]
This is what I see here:

https://github.com/Julian/lean.nvim/assets/329822/eee22758-68e5-4579-81c0-edf03b38528b

Will need some way of reproducing the broken behavior I think

**Comment by Julian** [comment]
To be sure -- are you using `lean.trythis.swap` or the code action here? You should be using the latter on Lean 4, given it exists now.

**Comment by grhkm21** [comment]
I was using trythis, and I have gotten it to work with code action now :) Thanks a lot!
