### ISSUE TITLE
Musl usage error message

### ISSUE THREAD

**Issue by foxyseta** [Julian/lean.nvim#324]
```
musl libc (x86_64)
Version 1.2.4_git20230717
Dynamik Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--]
```

This error shows up in stderr when using lean.nvim (curr is stuck as "Processing file..."). However, I can run every tool in my lean toolchain installation (`lean4:stable`) without problems.

I am using gcompat to run Lean on Alpine (which is a musl distribution).

**Comment by Julian** [comment]
Hey -- I'm likely happy to merge a PR fixing something here if you care to look into it, but am also probably unlikely to do so myself given I don't use such a system. Just letting you know!

**Comment by foxyseta** [comment]
No problem. Will make sure this is really not related to my Lean installation first.

**Comment by foxyseta** [comment]
It was a problem related to my installation after all. Sorry and thanks for this great project!

**Comment by Julian** [comment]
Glad you figured it out!
