### ISSUE TITLE
Entering edit mode will shrink line-number bar, moving text around

### ISSUE THREAD

**Issue by VictorTaelin** [Julian/lean.nvim#340]
When I enter edit mode using `lean.nvim`, the left bar (with line counts and infos) will change size, which causes the text to move around:

https://i.imgur.com/n38FQS8.mp4

I'm on OSX Sonoma, NVIM v0.10.0. Is this the expected behavior?

**Comment by Julian** [comment]
Hello!

That looks like it *should* be normal default neovim behavior there -- we've documented what to change if you don't like that behavior [here in the Wiki](https://github.com/Julian/lean.nvim/wiki/Configuring-&-Extending#preventing-the-progress-bars-from-horizontally-shifting-your-file) in the context of progress bars but I believe the same is what would cause your sign column shifting there in the screencast. Give that a shot and let me know if not?

**Comment by Julian** [comment]
Closing but if the above doesn't help feel free to follow-up!

**Comment by VictorTaelin** [comment]
Indeed, adding:

```
set signcolumn=yes
```

To my `init.vim` solved the issue. Thank you!
