### ISSUE TITLE
Infoview error fires whenever the current buffer changes

### ISSUE THREAD

**Issue by ray-kast** [Julian/lean.nvim#351]
I've been experiencing several issues with the infoview - upon changing any text in the associated buffer, an error fires:

```
Error executing lua callback: /opt/local/share/nvim/runtime/lua/vim/iter.lua:236: flatten() requires a list-like table
stack traceback:
        [C]: in function 'error'
        /opt/local/share/nvim/runtime/lua/vim/iter.lua:236: in function 'flatten'
        .../lean.nvim/lua/lean/infoview.lua:1091: in function <.../lean.nvim/lua/lean/infoview.lua:1087>
```

I have encountered several other errors that occur if I try to fix this one, but that may simply be because I don't know what I'm doing.

Versions:
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```
```
Lean (version 4.10.0, arm64-apple-darwin23.5.0, commit c375e19f6b65, Release)
clang version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: ~/.elan/toolchains/leanprover--lean4---v4.10.0/bin
Lake version 5.0.0-c375e19 (Lean version 4.10.0)
elan 3.1.0 (ce8551930 2024-02-19)
```
I have Lean installed via Elan using the `leanprover/lean4:v4.10.0` toolchain.

**Comment by Julian** [comment]
Does it happen with every/any lean code or just some specific one / is it deterministic? I think that sounds like something is going wrong with the (new) user widgets code, but not sure what yet (it will help if the answer is "just some specific lean code" hopefully)

**Comment by ray-kast** [comment]
@Julian It seems to be any code, any change to the buffer does this (although only if the infoview panel is open).

**Comment by ray-kast** [comment]
Okay, slight update - it seems sometimes it does not happen under some circumstances, there may be some specific component of my configuration causing this.

**Comment by Julian** [comment]
Do you have your dotfiles anywhere public perchance?

**Comment by ray-kast** [comment]
@Julian I do!  I have my nvim config [here](https://github.com/ray-kast/zrc/blob/c2b58438596b9d7ccecba81b43dd735f30ecfd6d/config/nvim/init.lua#L520-L532).

**Comment by monsterkrampe** [comment]
Similar issue here.
For me it's in line https://github.com/Julian/lean.nvim/blob/main/lua/lean/infoview.lua#L1088
```
Error executing lua callback: ...e/.local/share/nvim/lazy/lean.nvim/lua/lean/infoview.lua:1088: attempt to call field 'iter' (a nil value)
```

**Comment by Julian** [comment]
@monsterkrampe that error means you're on neovim 0.9. Upgrade to 0.10.

**Comment by monsterkrampe** [comment]
Indeed I am. I totally missed that this extension only supports 0.10 in its latest version. Sorry about that.
I'll come back here if the update does not fix things :)

**Comment by Julian** [comment]
I believe this should be fixed! Let me know if not
