### ISSUE TITLE
Infoview doesn't render until second update

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#60]
When first opening a file, the infoview doesn't display the first state of the file (until a second update e.g. by moving the cursor).

Most likely the CursorHold triggers before the server is ready.

Demo below (for Lean 3):

[![asciicast](https://asciinema.org/a/tnRXxLvEaC7CO2LVV6scxb2IJ.svg)](https://asciinema.org/a/tnRXxLvEaC7CO2LVV6scxb2IJ)

**Comment by rish987** [comment]
Should be resolved in Lean 4 by #85. Will investigate whether/how this is handled in `leanprover/vscode-lean` for Lean 3.

**Comment by Julian** [comment]
This looks fixed for Lean 3 as well now:

https://user-images.githubusercontent.com/329822/136055079-0e0d9990-c2c6-4d83-bdcc-94a4f25e2079.mov

So thanks for somehow fixing it at some point :D
