### ISSUE TITLE
Infoview width resizing is overzealous and resizes other windows

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#82]
Running `:tabe` with no filename, followed by `:vsplit foo.lean`–which both opens `foo.lean` as well as potentially autoopens an infoview–causes even `foo.lean`'s size to be set to 50.

**Comment by rish987** [comment]
Huh, I wasn't able to reproduce this:

[![asciicast](https://asciinema.org/a/EA0zqTiEOV74LjUDFVIxMGQKE.svg)](https://asciinema.org/a/EA0zqTiEOV74LjUDFVIxMGQKE)

Were those the right steps?

**Comment by Julian** [comment]
Sorry I meant to come back and update this, apologies.

Yeah those are the right steps, though I was referring to the middle window in your screencast (which obviously depends on `botright`) -- and basically that window gets squeezed. It's more noticeable if you have `width = 80` (or a narrower screen) where the new vsplitted middle window will be like 10 columns wide.

But there's not really anything we can do here about that, if someone wants to resize the first window they can ^W=.
