### ISSUE TITLE
Support infoview auto-close

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#86]
Currently, `:quit`ting the last Lean buffer in a tab leaves the infoview dangling in a detached state. Instead, it should automatically close the associated infoview, and `:close` should leave it in a detached state.

This will likely involve including the set of associated windows as part of the `Infoview` object, adding/removing these windows on Lean file `BufEnter`/`BufExit`, and once the last such buffer is exited, this will trigger the infoview to close as well. We should also make it (dynamically) configurable per-infoview whether or not this autoclose happens, in case someone doesn't like this -- that is, some kind of pin function that keeps the infoview around even when no Lean buffers are open.

**Comment by Julian** [comment]
What is the user-facing functionality that this is trying to support? Is it not just #84?

The second part of this sounds like #43, or is it trying to say something different?

**Comment by rish987** [comment]
Ah yes this is a dupe of #43, my bad!

**Comment by Julian** [comment]
All good just making sure I wasn't missing something!
