### ISSUE TITLE
Basic LSP functionality testing

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#91]
I'm realizing that #64 is probably actually very good to have, but this just isn't the right place for it. The "correct" way to go about this seems to be to upstream this to `nvim-lspconfig`, which would also protect us against any changes to that plugin.

**Comment by rish987** [comment]
(this is especially in light of the fix from neovim/nvim-lspconfig#1041, which we have essentially no test for at the moment)

**Comment by Julian** [comment]
Yeah! That does sound more like the right place, to ensure lspconfig works correctly with Lean, though I'm not sure they have any existing tests of that kind -- mjlbach may be amenable to it though.

**Comment by Julian** [comment]
We can close this right? It's upstream work?

Let me know if not.
