### ISSUE TITLE
Infoview updates slower in the presence of matchup (or any timer), and not at all when autocomplete pum is open

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#92]
We're running into two quite annoying neovim bugs.

One is where if you have e.g. [`vim-matchup`](https://github.com/Julian/dotfiles/blob/main/.config/nvim/init.vim#L50) enabled (as I personally do), or any other plugin which sets a [timer](https://github.com/neovim/neovim/blob/c1120ad0e1adf8b34ee10b63b2134fcb0d580fce/runtime/doc/usr_41.txt#L980-L985), then updates via `updatetime` see degraded performance (i.e. "the infoview updates slower").

The upstream neovim bug is [this one](https://github.com/neovim/neovim/issues/12587), and there are various downstream tracking bugs e.g. in matchup. There's a proposed [hack to fix via FixCursorHold.nvim](https://github.com/antoinemadec/FixCursorHold.nvim), but we'd need to tweak things a bit to recommend that (mostly because right now we use `setlocal updatetime` to configure the `CursorHold` time, whereas to use `FixCursorHold`, we would need to set a global option, `cursorhold_updatetime`). It may be that that's indeed worth doing though.

The second is even more annoying, which is that with `compe` enabled for autocompletion, `CursorHoldI` seems to not fire, or fire very sporadically, which means that in insert mode after calling `require'compe'.setup{}`, the infoview updates super unreliably.

I have to minimize what's needed to observe that behavior (it's not present in the minimal vimrc from this repo which is used for test cases), but I've already narrowed down that it is indeed related to enabling compe (which the tests do not do).

**Comment by gebner** [comment]
> but I've already narrowed down that it is indeed related to enabling compe

FWIW, I've enabled compe and the infoview updates just fine for me.
```lua
require'compe'.setup {
  enabled = true;
  autocomplete = false;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    nvim_lsp = true;
    -- emoji = true;
  };
}
```

**Comment by Julian** [comment]
Thanks, I'll compare my settings to yours.

**Comment by Julian** [comment]
So what's happening in the second "bug" has to do with autocomplete (which you have off) -- specifically `CursorHoldI` doesn't trigger when the pum is open. That's documented I see:

> CursorHoldI			Like CursorHold, but in Insert mode. Not
>				triggered when waiting for another key, e.g.
>				after CTRL-V, and not in CTRL-X mode
>				|insert_expand|.

but in a Lean buffer there's enough to complete everywhere that the infoview updates organically super rarely. I guess I personally don't care enough about autocomplete, it's just useful to me since I know so little Lean that it's like seeing suggestions as I type, but for now will just disable it. Probably deserves mentioning somewhere though, someone else will run into this given it's `compe`'s default. I tried also firing infoview updates via `TextChangedP`, which improves things but still doesn't behave fully correctly... So for now that's the best I got.

(This same thing happens with the signature help window open, e.g. via `lsp_signature.nvim`, which I was also playing with... so that too I disabled for Lean for now).

**Comment by gebner** [comment]
What we do in the vscode extension is listen to the cursor move event, and then use a timer so that it's only updated every 100ms or so.  (The timer also keeps running if the server is still processing the file.)  If we listened to cursor move events, we also wouldn't need to set `updatetime`.

Unfortunately, `CursorMovedI` seems to have the same caveat:
>				Not triggered when there is typeahead or when
>				an operator is pending.
>				Not triggered when the popup menu is visible.
