### ISSUE TITLE
Option to run tests sequentially (and as the default in CI)

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#94]
I've [observed MacOS CI failures](https://github.com/rish987/lean.nvim/runs/2890467750?check_suite_focus=true) in the past that were fixed by forcing tests to run sequentially. Fundamentally I believe the issue is that we're trying to run multiple Lean 4 servers for the same workspace at once. If we get to specifically wanting to test this (which seems like an unlikely scenario anyways), it  should be its own unit test.

Sequential tests may be a (little) bit slower, but I'd say it's worth it to make things more deterministic!

Pending nvim-lua/plenary.nvim#185.

**Comment by Julian** [comment]
Yeah... I've seen this too :/ Thanks for taking it upstream, I guess it's a reasonable option at least until we hit #93.

**Comment by rish987** [comment]
At this point I can't run tests locally without things timing out 😭 

Probably because my computer's on the slower side. Shouldn't be an issue for me once this is resolved though. Anyways I prefer the test results being printed in a deterministic order...

**Comment by Julian** [comment]
They're not speedy on mine either...

If you increase the timeouts they pass?

**Comment by rish987** [comment]
For me, no. Even if I increase the limit on `wait_for_ready_lsp()`, `wait_for_line_diagnostics()`, etc. it hits plenary-busted's built-in 50 second limit when attempting `infoview/lsp_spec.lua`.
