### ISSUE TITLE
Better display of zero-length diagnostics

### ISSUE THREAD

**Issue by gebner** [Julian/lean.nvim#97]
Lean likes to send diagnostics with a zero-length range.  At least for me, these don't render as squiggles in the editor (because there's zero characters to be highlighted...).  I'm not sure if this is a Lean bug or a neovim bug or just underspecified in the LSP.
```
▶ 34:14-34:14: error:
expected ':'
```

The easiest fix would probably be to extend the range by one character, but I'm not sure if we can intercept the diagnostics and modify them.

**Comment by Julian** [comment]
Is this Lean 3 or 4? In 3 I already noticed #7 where there were cases that VSCode properly underlined stuff and we didn't, but didn't investigate why.

But yeah we can fix this if it's as simple as

> extend the range by one character

I believe -- we'd override `vim.lsp.handlers['textDocument/publishDiagnostics']`.

**Comment by gebner** [comment]
I've just seen it in Lean 4.  And AFAICT every diagnostic sent by the Lean 3 lean-language-server is zero-range.
